org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.java.installations.auto-download=true
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.builtInKotlin=false
android.newDsl=false
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
org.gradle.configuration-cache=false
kotlin.daemon.jvmargs=-Xmx2048m
systemProp.kotlin.daemon.enabled=false
